// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang wasm-workers

// Tests for keywords fixtures. Cloudflare Workers with Vitest + Miniflare

import type { ExtractionResult } from "@kreuzberg/wasm";
import { extractBytes } from "@kreuzberg/wasm";
import { describe, expect, it } from "vitest";
import { assertions, buildConfig, getFixture, shouldSkipFixture } from "./helpers.js";

describe("keywords", () => {
	it("keywords_rake", async () => {
		const documentBytes = getFixture("pdf/fake_memo.pdf");
		if (documentBytes === null) {
			console.warn("[SKIP] Test skipped: fixture not available in Cloudflare Workers environment");
			return;
		}

		const config = buildConfig({ keywords: { algorithm: "rake", max_keywords: 10 } });
		let result: ExtractionResult | null = null;
		try {
			result = await extractBytes(documentBytes, "application/octet-stream", config);
		} catch (error) {
			if (shouldSkipFixture(error, "keywords_rake", ["keywords-rake"], undefined)) {
				return;
			}
			throw error;
		}
		if (result === null) {
			return;
		}
		assertions.assertExpectedMime(result, ["application/pdf"]);
		assertions.assertMinContentLength(result, 10);
		assertions.assertKeywords(result, true, 1, 10);
	});

	it("keywords_yake", async () => {
		const documentBytes = getFixture("pdf/fake_memo.pdf");
		if (documentBytes === null) {
			console.warn("[SKIP] Test skipped: fixture not available in Cloudflare Workers environment");
			return;
		}

		const config = buildConfig({ keywords: { algorithm: "yake", max_keywords: 10 } });
		let result: ExtractionResult | null = null;
		try {
			result = await extractBytes(documentBytes, "application/octet-stream", config);
		} catch (error) {
			if (shouldSkipFixture(error, "keywords_yake", ["keywords-yake"], undefined)) {
				return;
			}
			throw error;
		}
		if (result === null) {
			return;
		}
		assertions.assertExpectedMime(result, ["application/pdf"]);
		assertions.assertMinContentLength(result, 10);
		assertions.assertKeywords(result, true, 1, 10);
	});
});
