// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang wasm-deno

// Tests for keywords fixtures. Run with: deno test --allow-read

import type { ExtractionResult } from "./helpers.ts";
import { assertions, buildConfig, extractBytes, initWasm, resolveDocument, shouldSkipFixture } from "./helpers.ts";

// Initialize WASM module once at module load time
await initWasm();

Deno.test("keywords_rake", { permissions: { read: true } }, async () => {
	const documentBytes = await resolveDocument("pdf/fake_memo.pdf");
	const config = buildConfig({ keywords: { algorithm: "rake", max_keywords: 10 } });
	let result: ExtractionResult | null = null;
	try {
		// Sync file extraction - WASM uses extractBytes with pre-read bytes
		result = await extractBytes(documentBytes, "application/octet-stream", config);
	} catch (error) {
		if (shouldSkipFixture(error, "keywords_rake", ["keywords-rake"], undefined)) {
			return;
		}
		throw error;
	}
	if (result === null) {
		return;
	}
	assertions.assertExpectedMime(result, ["application/pdf"]);
	assertions.assertMinContentLength(result, 10);
	assertions.assertKeywords(result, true, 1, 10);
});

Deno.test("keywords_yake", { permissions: { read: true } }, async () => {
	const documentBytes = await resolveDocument("pdf/fake_memo.pdf");
	const config = buildConfig({ keywords: { algorithm: "yake", max_keywords: 10 } });
	let result: ExtractionResult | null = null;
	try {
		// Sync file extraction - WASM uses extractBytes with pre-read bytes
		result = await extractBytes(documentBytes, "application/octet-stream", config);
	} catch (error) {
		if (shouldSkipFixture(error, "keywords_yake", ["keywords-yake"], undefined)) {
			return;
		}
		throw error;
	}
	if (result === null) {
		return;
	}
	assertions.assertExpectedMime(result, ["application/pdf"]);
	assertions.assertMinContentLength(result, 10);
	assertions.assertKeywords(result, true, 1, 10);
});
